version: '2'
services:
  Pessoapostgres:
    container_name: Pessoaindividual
    image: postgres
    expose:
    - 1000
    ports:
     - "1000:1000"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=Pessoas
